name: 'Portfolio Deploy'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup node 10
        uses: actions/setup-node@v1
        with:
            node-version: 10.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
        env:
            CI: false
            NODE_ENV: production
      - name: Upload Build Directory
        uses: actions/upload-artifact@v1
        with:
            name: build
            path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Download Build Directory
          uses: actions/download-artifact@v1
          with:
              name: build

        - name: Deploy to Netlify
          uses: netlify/actions/cli@master
          env:
              NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          with:
              args: deploy --dir=build --prod
